# Generated by Django 5.2 on 2025-04-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('online', 'Online/E-commerce'), ('service', 'Service Provider'), ('financial', 'Financial Services'), ('gambling', 'Gambling/Gaming'), ('travel', 'Travel/Hospitality'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('flagged', 'Flagged for Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Risk')], max_length=20, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_data', models.JSONField(blank=True, null=True)),
                ('external_api_response', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_merchants', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create Merchant'), ('update', 'Update Merchant'), ('verify', 'Verify Merchant'), ('flag', 'Flag Merchant'), ('review', 'Review Merchant'), ('reject', 'Reject Merchant'), ('report', 'Generate Report')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='merchant_verification.merchant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_transaction_volume', models.IntegerField(blank=True, null=True)),
                ('high_risk_countries_percentage', models.FloatField(blank=True, null=True)),
                ('unusual_hours_percentage', models.FloatField(blank=True, null=True)),
                ('similar_transactions_percentage', models.FloatField(blank=True, null=True)),
                ('chargeback_rate', models.FloatField(blank=True, null=True)),
                ('transaction_data', models.JSONField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_patterns', to='merchant_verification.merchant')),
            ],
            options={
                'verbose_name': 'Transaction Pattern',
                'verbose_name_plural': 'Transaction Patterns',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='VerificationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('suspicious_website', 'Suspicious Website Content'), ('missing_info', 'Missing Critical Information'), ('high_risk_location', 'High Risk Location'), ('transaction_pattern', 'Unusual Transaction Pattern'), ('external_data', 'External Data Discrepancy'), ('regulatory', 'Regulatory Concern'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_flags', to='merchant_verification.merchant')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Flag',
                'verbose_name_plural': 'Verification Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField()),
                ('risk_assessment', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports', to='merchant_verification.merchant')),
            ],
            options={
                'verbose_name': 'Verification Report',
                'verbose_name_plural': 'Verification Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
